{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import math\n",
    "import turtle \n",
    "xz=turtle.Turtle()\n",
    "wn=turtle.Screen()\n",
    "wn.title('welcome to the solar system!')\n",
    "wn.bgcolor('black')\n",
    "wn.setworldcoordinates(-500,-500,750,750)\n",
    "xz.color('red')\n",
    "xz.speed(0)\n",
    "xz.shape(\"circle\")\n",
    "xz.up()\n",
    "xz.goto(-30,0)\n",
    "xz.down()\n",
    "\n",
    "a1=70;b1=48\n",
    "\n",
    "a=xz.clone()\n",
    "a.color('blue')\n",
    "a.up()\n",
    "a.goto(0,b1)\n",
    "a.down()\n",
    "\n",
    "b=xz.clone()\n",
    "b.color('green')\n",
    "b.up()\n",
    "b.goto(20,1.5*b1)\n",
    "b.down()\n",
    "b.lt(90)\n",
    "\n",
    "c=xz.clone()\n",
    "c.color('yellow')\n",
    "c.up()\n",
    "c.goto(30,1.9*b1)\n",
    "c.down()\n",
    "c.lt(180)\n",
    "\n",
    "d=xz.clone()\n",
    "d.color('purple')\n",
    "d.up()\n",
    "d.goto(44,2.4*b1)\n",
    "d.down()\n",
    "d.rt(90)\n",
    "\n",
    "e=xz.clone()\n",
    "e.color('orange')\n",
    "e.up()\n",
    "e.goto(60,3.0*b1)\n",
    "e.down()\n",
    "\n",
    "f=xz.clone()\n",
    "f.color('pink')\n",
    "f.up()\n",
    "f.goto(70,4.0*b1)\n",
    "f.down()\n",
    "f.lt(180)\n",
    "\n",
    "g=xz.clone()\n",
    "g.color('grey')\n",
    "g.up()\n",
    "g.goto(80,5.0*b1)\n",
    "g.down()\n",
    "g.rt(90)\n",
    "\n",
    "for t in range(30000):\n",
    "    a.goto(a1*math.sin(t/10),b1*math.cos(t/10))\n",
    "    b.goto(1.5*(a1*math.sin(t/20))+20,1.5*(b1*math.cos(t/20)))\n",
    "    c.goto(1.9*(a1*math.sin(t/30))+30,1.9*(b1*math.cos(t/30)))\n",
    "    d.goto(2.4*(a1*math.sin(t/40))+44,2.4*(b1*math.cos(t/40)))  \n",
    "    e.goto(3*(a1*math.sin(t/60))+60,3*(b1*math.cos(t/60)))\n",
    "    f.goto(4*(a1*math.sin(t/80))+70,4*(b1*math.cos(t/80)))\n",
    "    g.goto(5*(a1*math.sin(t/100))+80,5*(b1*math.cos(t/100)))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
